### ISSUE TITLE
Add an option to use an already installed pugixml instead of using the vendored version

### ISSUE THREAD

**Issue by traversaro** [robotology/diagnostic-daemon#10]
This is not urgent, but it is a prerequisite for https://github.com/robotology/robotology-superbuild/issues/430 .

**Comment by traversaro** [comment]
I think this was fixed by https://github.com/robotology/diagnostic-daemon/pull/9, what do you think @Nicogene @triccyx ?

**Comment by Nicogene** [comment]
Yes! Closing
