### ISSUE TITLE
COMPILE_WITHYARP not present

### ISSUE THREAD

**Issue by traversaro** [robotology/diagnostic-daemon#13]
In the README the option COMPILE_WITHYARP  is mentioned, but it is not actually present in the CMake.

**Comment by triccyx** [comment]
Ok we have an error in doc:
```COMPILE_WITHYARP_DEF```

**Comment by triccyx** [comment]
See:
https://github.com/robotology/diagnostic-daemon/commit/4e1d98e380c14c5094bc099496a668bc23359fd7
@Nicogene
